name: 'Bug report'
description: 'Report a bug to help us improve'
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'What happened? What did you expect?'
      placeholder: 'Clear, concise description of the bug.'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 'Steps to reproduce'
      placeholder: '1) ... 2) ... 3) ...'
  - type: input
    id: environment
    attributes:
      label: 'Environment'
      placeholder: 'OS, Browser/Node version, etc.'
  - type: textarea
    id: logs
    attributes:
      label: 'Logs/screenshots'
