name: 'Feature request'
description: 'Suggest an idea for this project'
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: 'Problem to solve'
      placeholder: 'What problem does this feature solve?'
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 'Proposed solution'
      placeholder: "Describe the solution you'd like"
  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives considered'
  - type: textarea
    id: additional
    attributes:
      label: 'Additional context'
