name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile || yarn install
          else
            yarn install
          fi

      - name: Show versions
        run: |
          node -v
          yarn -v

      - name: Lint (if script exists)
        run: |
          node -e "const s=require('./package.json').scripts||{}; process.exit(s.lint?0:1)" && yarn lint || echo "No lint script; skipping."

      - name: Test (if script exists)
        run: |
          node -e "const s=require('./package.json').scripts||{}; process.exit(s.test?0:1)" && yarn test --ci || echo "No test script; skipping."

      - name: Build (if script exists)
        run: |
          node -e "const s=require('./package.json').scripts||{}; process.exit(s.build?0:1)" && yarn build || echo "No build script; skipping."
